"""empty message

Revision ID: 0f71a24751e8
Revises: 
Create Date: 2019-04-15 12:51:06.364580

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f71a24751e8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('biorxiv',
    sa.Column('source', sa.String(length=10), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('parse_status', sa.Integer(), nullable=False),
    sa.Column('parse_data', sa.String(), nullable=True),
    sa.Column('pages', sa.String(), nullable=False),
    sa.Column('page_count', sa.Integer(), nullable=False),
    sa.Column('posted_date', sa.String(length=10), nullable=True),
    sa.Column('author_contact', sa.String(), nullable=True),
    sa.Column('email_sent', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('biorxiv')
    # ### end Alembic commands ###
